### ISSUE TITLE
Create a basic web crawler

### ISSUE THREAD

**Issue by pvandorp** [pvandorp/qsec-008#1]
Create a Crawl method that takes a Url and returns a list of Urls.

Implement the Crawl method so that it:
- Requests the provided URL
- Verifies the returned page contains HTML
- Finds all `<a>` tags in the HTML
- Retrieves the href= attribute value of the found <a> tags
- Returns a list of found URLs

**Comment by haraldfianbakken** [comment]
I'll do this one!
